# carbonio-oidc-connector upstream
# Install path: /opt/zextras/conf/nginx/extensions/upstream-oidc.conf
# Owner: zextras:zextras
# Included in http{} context

upstream oidc_connector {
    server 127.0.0.1:8754;
    keepalive 4;
}
